image: python:latest

stages:
  - scrape
  - git_commit_stage

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V # Print out python version for debugging
  - pip install -r app_deploy_data/fire_data_parsing/scraper-requirements.txt

scrape:
  stage: scrape
  script:
  - python app_deploy_data/fire_data_parsing/parse_fire_report_json.py.py

