# todo: version 2 for compatibility with Chombo- switch to 3
version: '2'

services:
  web:
    restart: always
    build: .
    container_name: escos_web_penguin
    expose:
      - "8000"
    links:
      - postgres_db:postgres_db
    command: /escalation/boot.sh
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
    networks:
      - demo_network

  data:
    image: postgres:latest
    volumes:
      - db-data-penguin:/var/lib/postgresql/data
    command: "true"
    networks:
      - demo_network

  postgres_db:
    restart: always
    image: postgres:latest
    container_name: escos_db_penguin
    env_file:
    - ./escalation/app_deploy_data/database_env_file
    volumes:
      - db-data-penguin:/var/lib/postgresql/data
#      This file runs a db setup command that creates the upload metadata table
      - ./escalation/database/container_db_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - demo_network


volumes:
  db-data-penguin:

networks:
  demo_network:
    external:
      name: escalation-demo-network